# Generated by Django 4.2.3 on 2023-07-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasks',
            table='Task',
        ),
    ]
